### ISSUE TITLE
Unnecessary loading of training images while testing.

### ISSUE THREAD

**Issue by grassknoted** [grassknoted/CDAE4InfoExtraction#2]
While running ```test_model.py``` for testing the model, all the training images are loaded, which slows everything down.

**Comment by akhil-reddy** [comment]
Did you figure out why it's happening?

**Comment by grassknoted** [comment]
@akhil-reddy Yeah, I know the problem. I'll work on fixing it soon.

**Comment by akhil-reddy** [comment]
Is this solved?

**Comment by grassknoted** [comment]
Yes this issue was resolved with one of the previous commits.
