### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by aditisrinivas97** [grassknoted/CDAE4InfoExtraction#6]
Please fix the broken image links in the README

<img width="1000" alt="screenshot 2019-01-27 at 5 47 46 pm" src="https://user-images.githubusercontent.com/14026006/51800853-f0de9c80-225b-11e9-9f73-5c6cbca6fe42.png">

**Comment by grassknoted** [comment]
Thanks for pointing this out @aditisrinivas97 . This is the same as #3 . @akhil-reddy will handle it.
